import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { statSync } from 'node:fs';
import {
  ClusterConfigSchema,
  ModImportRequestSchema,
  ProjectModsUpdateSchema,
  ProjectConfigUpdateSchema,
  ProjectCreateSchema,
  TargetConfigSchema,
  createDefaultClusterConfig,
  createRemoteDeployPath,
  renderComposeFile,
  renderConfigPreview,
  renderModoverrides,
  renderModsSetup,
  type ClusterConfig,
  type ModImportResult,
  type ModRecommendationBundle,
  type ModSearchResponse,
  type ProjectAction,
  type ProjectConfigUpdateInput,
  type ProjectCreateInput,
  type ProjectDetail,
  type ProjectModsDetail,
  type ProjectModsUpdateInput,
  type ServerStats,
  type TargetConfig,
} from '@dst-launcher/shared';
import { ProjectRepository } from '../db/repository';
import { EventBus } from './event-bus';
import { resolveInstancePaths, type AppPaths } from '../utils/paths';
import { runCommand } from '../utils/command';
import type { RuntimeAdapter } from '../adapters/base';
import { LocalDockerAdapter } from '../adapters/local-docker';
import { SshDockerAdapter } from '../adapters/ssh-docker';
import { NativeAdapter } from '../adapters/native-adapter';
import { tunnelService } from './tunnel-service';
import { SteamWorkshopProvider } from './steam-workshop-provider';

// DST Launcher init script — mounted at /home/dst/config/launcher.sh.
// Avoids bind-mounting over /home/dst/steamcmd.sh, which causes SteamCMD's self-update to
// segfault (cross-filesystem atomic rename, EXDEV error).
// Instead: calls the SteamCMD binary directly (no 'validate'), writes our custom
// dedicated_server_mods_setup.lua, replaces steamcmd.sh with a no-op, then exec's the
// original entrypoint so all cluster config/shard setup still runs normally.
const DST_LAUNCHER_SH = `#!/bin/bash
# Generated by DST Launcher
export LD_LIBRARY_PATH="/home/dst/linux32:\${LD_LIBRARY_PATH-}"
ulimit -n 2048

STEAMCMD=/home/dst/linux32/steamcmd
MAGIC_RESTART=42
MAX_RETRIES=5
RETRY_DELAY=10

echo "[DST Launcher] Starting SteamCMD update..."

# Retry loop — SteamCMD can fail transiently (DNS not ready, network blip, etc.)
for attempt in \$(seq 1 \$MAX_RETRIES); do
  echo "[DST Launcher] SteamCMD attempt \$attempt/\$MAX_RETRIES"

  # Inner loop handles MAGIC_RESTART (exit code 42 = SteamCMD self-update)
  while true; do
    \$STEAMCMD +@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 \\
      +force_install_dir /home/dst/dst_server +login anonymous +app_update 343050 +quit
    STATUS=\$?
    echo "[DST Launcher] SteamCMD exited with status \$STATUS"
    [ \$STATUS -ne \$MAGIC_RESTART ] && break
    echo "[DST Launcher] SteamCMD requested restart (self-update), restarting..."
  done

  # Verify the game was actually downloaded
  if [ -d /home/dst/dst_server/bin ]; then
    echo "[DST Launcher] DST server downloaded successfully."
    break
  fi

  echo "[DST Launcher] ERROR: /home/dst/dst_server/bin not found (attempt \$attempt/\$MAX_RETRIES)"
  if [ \$attempt -lt \$MAX_RETRIES ]; then
    echo "[DST Launcher] Retrying in \${RETRY_DELAY}s..."
    sleep \$RETRY_DELAY
    RETRY_DELAY=\$((RETRY_DELAY * 2))
  fi
done

# If download still failed after all retries, exit so Docker can restart us (with backoff)
if [ ! -d /home/dst/dst_server/bin ]; then
  echo "[DST Launcher] FATAL: Failed to download DST server after \$MAX_RETRIES attempts."
  sleep 30
  exit 1
fi

# Write our custom mods setup AFTER SteamCMD (validate can no longer reset it)
if [ -f /home/dst/config/mods_setup.lua ]; then
  mkdir -p /home/dst/dst_server/mods
  cp /home/dst/config/mods_setup.lua /home/dst/dst_server/mods/dedicated_server_mods_setup.lua
fi

# Replace steamcmd.sh with a no-op so the original entrypoint skips its SteamCMD call
printf '#!/bin/bash\\n# steamcmd already ran via DST Launcher init\\nexit 0\\n' > /home/dst/steamcmd.sh
chmod +x /home/dst/steamcmd.sh

# Run the original entrypoint (cluster config, shard setup, DST server start)
echo "[DST Launcher] Handing off to entrypoint.sh..."
exec /home/dst/data/entrypoint.sh
`;

export class ProjectService {
  constructor(
    private readonly repository: ProjectRepository,
    private readonly eventBus: EventBus,
    private readonly paths: AppPaths,
    private readonly workshopProvider = new SteamWorkshopProvider(),
  ) {}

  async listProjects() {
    return this.repository.listProjects();
  }

  async createProject(input: ProjectCreateInput) {
    const parsed = ProjectCreateSchema.parse({
      ...input,
      clusterConfig: input.clusterConfig ?? createDefaultClusterConfig(input.name),
      target: normalizeTarget(input.target, input.slug),
    });

    const projectId = await this.repository.createProject(parsed);
    await this.prepareProjectFiles(projectId);
    return this.getProject(projectId);
  }

  async getProject(projectId: string): Promise<ProjectDetail> {
    const detail = await this.repository.getProjectDetail(projectId);
    const ports = getProjectPorts(detail.clusterConfig, detail.target.type);
    const [runtime, network] = await Promise.all([
      this.getRuntime(detail.target, detail.slug, detail.deployment?.composePath ?? null),
      this.createAdapter(detail.target, detail.slug).inspectNetwork(detail.target, ports),
    ]);

    // Attach tunnel status if active
    const ts = tunnelService.status(detail.slug);
    const tunnel = ts.active || ts.claimUrl || ts.error
      ? {
          active: ts.active,
          publicHost: ts.info?.publicHost ?? '',
          portMappings: ts.info?.portMappings ?? [],
          error: ts.claimUrl
            ? `请在浏览器中完成认证: ${ts.claimUrl}`
            : ts.error ?? '',
        }
      : undefined;

    return {
      ...detail,
      network,
      runtime,
      tunnel,
    };
  }

  async updateProject(projectId: string, input: ProjectConfigUpdateInput) {
    const parsed = ProjectConfigUpdateSchema.parse({
      ...input,
      target: normalizeTarget(input.target, (await this.repository.getProjectDetail(projectId)).slug),
      clusterConfig: ClusterConfigSchema.parse(input.clusterConfig),
    });

    await this.repository.updateProject(projectId, parsed);
    await this.prepareProjectFiles(projectId);
    return this.getProject(projectId);
  }

  async searchMods(query: string, page = 1): Promise<ModSearchResponse> {
    const response = await this.workshopProvider.search(query, page);
    await this.repository.upsertModCacheItems(response.items);
    return response;
  }

  async getRecommendations(): Promise<ModRecommendationBundle[]> {
    const bundles = await this.workshopProvider.getRecommendations();
    await this.repository.upsertModCacheItems(bundles.flatMap((bundle) => bundle.items));
    return bundles;
  }

  async importMods(value: string): Promise<ModImportResult> {
    const parsed = ModImportRequestSchema.parse({ value });
    const result = await this.workshopProvider.import(parsed.value);
    await this.repository.upsertModCacheItems(result.items);
    return result;
  }

  async getProjectMods(projectId: string): Promise<ProjectModsDetail> {
    return await this.repository.getProjectModsDetail(projectId);
  }

  async updateProjectMods(projectId: string, input: ProjectModsUpdateInput): Promise<ProjectModsDetail> {
    const parsed = ProjectModsUpdateSchema.parse(input);
    const cached = await this.repository.getCachedMods(parsed.entries.map((item) => item.workshopId));
    const cachedIds = new Set(cached.map((item) => item.workshopId));
    const missingIds = parsed.entries.map((item) => item.workshopId).filter((workshopId) => !cachedIds.has(workshopId));

    if (missingIds.length > 0) {
      const details = await this.workshopProvider.getPublishedFileDetails(missingIds);
      await this.repository.upsertModCacheItems(details);
    }

    await this.repository.replaceProjectModEntries(projectId, parsed.entries);
    await this.prepareProjectFiles(projectId);
    return await this.repository.getProjectModsDetail(projectId);
  }

  async testTarget(target: TargetConfig, slug?: string) {
    const adapter = this.createAdapter(target, slug);
    return adapter.testConnection();
  }

  async getProjectStats(projectId: string): Promise<ServerStats> {
    const project = await this.repository.getProjectDetail(projectId);
    if (project.target.type === 'ssh') {
      return collectRemoteStats(project.target);
    }
    const diskPath = project.target.type === 'native'
      ? (project.target.installPath || '/')
      : resolveInstancePaths(this.paths.instancesDir, project.slug).instanceDir;
    return collectLocalStats(diskPath);
  }

  async runAction(projectId: string, action: ProjectAction) {
    const project = await this.repository.getProjectDetail(projectId);
    const adapter = this.createAdapter(project.target, project.slug);
    const task = await this.repository.createTask(projectId, action, `开始执行 ${action}`);
    this.eventBus.publishTask({
      type: 'task.started',
      projectId,
      taskId: task.id,
      action,
      message: `开始执行 ${action}`,
      timestamp: new Date().toISOString(),
    });

    try {
      const paths = resolveInstancePaths(this.paths.instancesDir, project.slug);
      const ports = getProjectPorts(project.clusterConfig, project.target.type);
      let message = '';
      let networkMessage = '';

      switch (action) {
        case 'deploy': {
          if (project.target.type === 'ssh') {
            networkMessage = await adapter.ensureFirewall(project.target, ports, project.slug);
          }
          await this.prepareProjectFiles(projectId);
          await this.syncIfNeeded(project.target, paths.root, adapter);
          await this.repository.touchDeployment(projectId);
          message = joinMessages(
            networkMessage,
            project.target.type === 'ssh'
              ? `部署文件已同步到 ${project.target.remotePath}`
              : `部署文件已生成到 ${paths.root}`,
          );
          break;
        }
        case 'start': {
          if (project.target.type === 'ssh') {
            networkMessage = await adapter.ensureFirewall(project.target, ports, project.slug);
          }
          await this.prepareProjectFiles(projectId);
          await this.syncIfNeeded(project.target, paths.root, adapter);
          message = joinMessages(
            networkMessage,
            await adapter.composeUp(
              project.target.type === 'native' ? '' : paths.composeFile,
              project.slug,
            ),
          );
          await this.repository.setProjectStatus(projectId, 'running');
          break;
        }
        case 'stop': {
          const cf = project.target.type === 'native' ? '' : paths.composeFile;
          message = await adapter.composeStop(cf, project.slug);
          await this.repository.setProjectStatus(projectId, 'stopped');
          break;
        }
        case 'restart': {
          await this.prepareProjectFiles(projectId);
          await this.syncIfNeeded(project.target, paths.root, adapter);
          const cf = project.target.type === 'native' ? '' : paths.composeFile;
          message = await adapter.composeRestart(cf, project.slug);
          await this.repository.setProjectStatus(projectId, 'running');
          break;
        }
        case 'update': {
          await this.prepareProjectFiles(projectId);
          await this.syncIfNeeded(project.target, paths.root, adapter);
          const cf = project.target.type === 'native' ? '' : paths.composeFile;
          message = await adapter.composeUpdate(cf, project.slug);
          await this.repository.setProjectStatus(projectId, 'running');
          break;
        }
        case 'backup': {
          message = await this.backupProject(projectId);
          break;
        }
        case 'check-ports': {
          const check = await adapter.checkPorts(project.target, ports);
          message = `${check.message}\n${check.detail}`.trim();
          break;
        }
        case 'ensure-firewall': {
          message = await adapter.ensureFirewall(project.target, ports, project.slug);
          break;
        }
        case 'install-server': {
          if (project.target.type !== 'native') {
            throw new Error('install-server 仅适用于 native 模式');
          }
          const nativeAdapter = adapter as import('../adapters/native-adapter').NativeAdapter;
          this.publishTaskProgress(projectId, task.id, action, '开始安装/更新 DST 服务端...');
          message = await nativeAdapter.installServer({
            onStdout: (line) => {
              this.publishTaskProgress(projectId, task.id, action, line);
              this.publishActionLog(projectId, line, 'stdout');
            },
            onStderr: (line) => {
              this.publishTaskProgress(projectId, task.id, action, line);
              this.publishActionLog(projectId, line, 'stderr');
            },
          });
          break;
        }
        case 'start-tunnel': {
          const tunnelDir = path.join(paths.root, 'tunnel');
          this.publishTaskProgress(projectId, task.id, action, '启动 NAT 穿透...');
          await tunnelService.start(project.slug, tunnelDir, ports, {
            onStdout: (line) => {
              this.publishTaskProgress(projectId, task.id, action, line);
              this.publishActionLog(projectId, line, 'stdout');
            },
            onStderr: (line) => {
              this.publishActionLog(projectId, line, 'stderr');
            },
          });
          // Wait a few seconds for tunnel to establish
          await new Promise((resolve) => setTimeout(resolve, 5000));
          const tunnelStatus = tunnelService.status(project.slug);
          if (tunnelStatus.claimUrl) {
            message = `需要认证，请在浏览器中打开: ${tunnelStatus.claimUrl}`;
          } else if (tunnelStatus.info?.publicHost) {
            message = `隧道已建立: ${tunnelStatus.info.publicHost}`;
          } else if (tunnelStatus.error) {
            message = tunnelStatus.error;
          } else {
            message = 'playit 已启动，等待隧道建立...';
          }
          break;
        }
        case 'stop-tunnel': {
          await tunnelService.stop(project.slug);
          message = 'NAT 穿透已停止';
          break;
        }
        case 'reset-world': {
          const cf = project.target.type === 'native' ? '' : paths.composeFile;
          const clusterName = project.clusterConfig.clusterName;
          // Stop containers first
          await adapter.composeStop(cf, project.slug);
          // Delete save directories based on target type
          if (project.target.type === 'ssh') {
            const { runCommand } = await import('../utils/command');
            const remoteSaveDir = path.posix.join(project.target.remotePath, 'data', 'cluster', clusterName);
            await runCommand('ssh', [
              '-i', project.target.privateKeyPath,
              '-p', String(project.target.port),
              '-o', 'BatchMode=yes',
              '-o', 'StrictHostKeyChecking=accept-new',
              `${project.target.username}@${project.target.host}`,
              `rm -rf "${remoteSaveDir}/Master/save" "${remoteSaveDir}/Caves/save"`,
            ]);
          } else if (project.target.type === 'local') {
            const dockerClusterDir = path.join(paths.clusterDir, clusterName);
            await fs.rm(path.join(dockerClusterDir, 'Master', 'save'), { recursive: true, force: true });
            await fs.rm(path.join(dockerClusterDir, 'Caves', 'save'), { recursive: true, force: true });
          } else if (project.target.type === 'native') {
            await fs.rm(path.join(paths.clusterDir, 'Master', 'save'), { recursive: true, force: true });
            await fs.rm(path.join(paths.clusterDir, 'Caves', 'save'), { recursive: true, force: true });
          }
          // Restart server
          await this.prepareProjectFiles(projectId);
          await this.syncIfNeeded(project.target, paths.root, adapter);
          message = await adapter.composeUp(cf, project.slug);
          message = '世界已重置并重新启动。';
          await this.repository.setProjectStatus(projectId, 'running');
          break;
        }
        case 'prefetch-mods': {
          const mods = await this.repository.getProjectModsDetail(projectId);
          if (mods.summary.totalSelected === 0) {
            message = '当前项目还没有配置模组，无需预拉取。';
            break;
          }

          await this.prepareProjectFiles(projectId);
          await this.syncIfNeeded(project.target, paths.root, adapter);
          const runtime = await this.getRuntime(project.target, project.slug, paths.composeFile);
          if (runtime.containers.some((item) => item.state === 'running')) {
            throw new Error('项目当前正在运行，请先停止服务，再执行模组预拉取。');
          }

          this.publishTaskProgress(projectId, task.id, action, '开始执行模组预拉取，日志会同步写入工作台。');
          message = await adapter.prefetchMods(paths.composeFile, project.slug, {
            onStdout: (line) => {
              this.publishTaskProgress(projectId, task.id, action, line);
              this.publishActionLog(projectId, line, 'stdout');
            },
            onStderr: (line) => {
              this.publishTaskProgress(projectId, task.id, action, line);
              this.publishActionLog(projectId, line, 'stderr');
            },
          });
          await this.repository.markProjectModsPrefetch(projectId, 'success', '最近一次预拉取成功。');
          await this.prepareProjectFiles(projectId);
          break;
        }
      }

      await this.repository.updateTask(task.id, 'success', message);
      this.eventBus.publishTask({
        type: 'task.finished',
        projectId,
        taskId: task.id,
        action,
        message,
        timestamp: new Date().toISOString(),
      });
      this.eventBus.publishTask({
        type: 'status.changed',
        projectId,
        status: (await this.repository.getProjectDetail(projectId)).status,
        timestamp: new Date().toISOString(),
      });
      this.eventBus.publishLog({
        type: 'log.line',
        projectId,
        line: message,
        stream: 'system',
        timestamp: new Date().toISOString(),
      });
      return { ok: true };
    } catch (error) {
      const message = error instanceof Error ? error.message : '未知错误';
      if (action === 'prefetch-mods') {
        await this.repository.markProjectModsPrefetch(projectId, 'failed', message);
      }
      await this.repository.updateTask(task.id, 'failed', message);
      await this.repository.setProjectStatus(projectId, 'error');
      this.eventBus.publishTask({
        type: 'task.failed',
        projectId,
        taskId: task.id,
        action,
        message,
        timestamp: new Date().toISOString(),
      });
      this.eventBus.publishTask({
        type: 'status.changed',
        projectId,
        status: 'error',
        timestamp: new Date().toISOString(),
      });
      throw error;
    }
  }

  async streamLogs(projectId: string, onLine: (line: string, stream: 'stdout' | 'stderr' | 'system') => void) {
    const project = await this.repository.getProjectDetail(projectId);
    const adapter = this.createAdapter(project.target, project.slug);
    const paths = resolveInstancePaths(this.paths.instancesDir, project.slug);

    return adapter.streamComposeLogs(paths.composeFile, project.slug, {
      onStdout: (line) => onLine(line, 'stdout'),
      onStderr: (line) => onLine(line, 'stderr'),
    });
  }

  private async prepareProjectFiles(projectId: string) {
    const detail = await this.repository.getProjectDetail(projectId);
    const paths = resolveInstancePaths(this.paths.instancesDir, detail.slug);
    await fs.mkdir(paths.configDir, { recursive: true });
    await fs.mkdir(paths.serverDir, { recursive: true });
    await fs.mkdir(paths.backupsDir, { recursive: true });

    const preview = renderConfigPreview(detail.clusterConfig, { targetType: detail.target.type });
    await writeRenderedFiles(paths.configDir, preview);

    // Build mod content from workbench entries (only enabled mods)
    const modsDetail = await this.repository.getProjectModsDetail(projectId);
    const { resolvedModIds } = modsDetail.summary;
    // Use pre-computed preview which already filters to enabled entries only
    const modsSetupContent = modsDetail.preview.modsSetup;
    const modoverridesContent = renderModoverrides(resolvedModIds);

    if (detail.target.type === 'native') {
      // Native mode: config files go directly in clusterDir (server uses -cluster .)
      await fs.mkdir(path.join(paths.clusterDir, 'Master'), { recursive: true });
      await fs.mkdir(path.join(paths.clusterDir, 'Caves'), { recursive: true });
      await writeClusterRuntimeFiles(paths.clusterDir, preview);
      // Native mode: dedicated_server_mods_setup.lua goes in the server's mods/ directory
      const modsDir = path.join(paths.nativeServerDir, 'mods');
      await fs.mkdir(modsDir, { recursive: true });
      await fs.writeFile(path.join(modsDir, 'dedicated_server_mods_setup.lua'), modsSetupContent, 'utf8');
      // modoverrides.lua for each shard
      await fs.writeFile(path.join(paths.clusterDir, 'Master', 'modoverrides.lua'), modoverridesContent, 'utf8');
      await fs.writeFile(path.join(paths.clusterDir, 'Caves', 'modoverrides.lua'), modoverridesContent, 'utf8');
      await this.repository.upsertDeployment(projectId, '', paths.root, false);
    } else {
      // Docker mode: config files go in clusterDir/<clusterName>/ subdirectory
      // The Docker image (wollwolke/dst-dedicated-server) uses CLUSTER_NAME as -cluster arg,
      // so DST looks for configs at /data/<clusterName>/
      const dockerClusterDir = path.join(paths.clusterDir, detail.clusterConfig.clusterName);
      await fs.mkdir(path.join(dockerClusterDir, 'Master'), { recursive: true });
      await fs.mkdir(path.join(dockerClusterDir, 'Caves'), { recursive: true });
      await writeClusterRuntimeFiles(dockerClusterDir, preview);
      // dedicated_server_mods_setup.lua → /home/dst/dst_server/mods/ (volume: ../data/server)
      const dockerModsDir = path.join(paths.serverDir, 'mods');
      await fs.mkdir(dockerModsDir, { recursive: true });
      await fs.writeFile(path.join(dockerModsDir, 'dedicated_server_mods_setup.lua'), modsSetupContent, 'utf8');
      // modoverrides.lua → each shard dir inside cluster
      await fs.writeFile(path.join(dockerClusterDir, 'Master', 'modoverrides.lua'), modoverridesContent, 'utf8');
      await fs.writeFile(path.join(dockerClusterDir, 'Caves', 'modoverrides.lua'), modoverridesContent, 'utf8');
      // launcher.sh → mounted at /home/dst/config/launcher.sh (used as docker entrypoint)
      // mods_setup.lua → mounted at /home/dst/config/mods_setup.lua (copied after SteamCMD runs)
      const configDir = path.join(paths.root, 'config');
      await fs.mkdir(configDir, { recursive: true });
      await fs.writeFile(path.join(configDir, 'launcher.sh'), DST_LAUNCHER_SH, { encoding: 'utf8', mode: 0o755 });
      await fs.writeFile(path.join(configDir, 'mods_setup.lua'), modsSetupContent, 'utf8');
      await fs.mkdir(paths.composeDir, { recursive: true });
      const compose = renderComposeFile({
        slug: detail.slug,
        clusterConfig: detail.clusterConfig,
      });
      await fs.writeFile(paths.composeFile, compose, 'utf8');
      await this.repository.upsertDeployment(
        projectId,
        paths.composeFile,
        detail.target.type === 'ssh' ? detail.target.remotePath : paths.root,
        false,
      );
    }
  }

  private createAdapter(target: TargetConfig, slug?: string): RuntimeAdapter {
    if (target.type === 'local') {
      return new LocalDockerAdapter(target);
    }
    if (target.type === 'native') {
      const instancePaths = resolveInstancePaths(this.paths.instancesDir, slug ?? 'default');
      return new NativeAdapter(target, instancePaths);
    }
    return new SshDockerAdapter(target);
  }

  private async getRuntime(target: TargetConfig, slug: string, composeFile: string | null) {
    const adapter = this.createAdapter(target, slug);
    const check = await adapter.testConnection();

    if (target.type === 'native') {
      try {
        const containers = await adapter.composePs('', slug);
        return { dockerAvailable: check.ok, containers };
      } catch {
        return { dockerAvailable: check.ok, containers: [] };
      }
    }

    if (!composeFile) {
      return { dockerAvailable: check.ok, containers: [] };
    }

    try {
      const containers = await adapter.composePs(composeFile, slug);
      return { dockerAvailable: check.ok, containers };
    } catch {
      return { dockerAvailable: check.ok, containers: [] };
    }
  }

  private async syncIfNeeded(target: TargetConfig, localRoot: string, adapter: RuntimeAdapter) {
    if (target.type === 'ssh' && adapter.syncInstance) {
      await adapter.syncInstance(localRoot, target);
    }
  }

  private async backupProject(projectId: string): Promise<string> {
    const detail = await this.repository.getProjectDetail(projectId);
    const paths = resolveInstancePaths(this.paths.instancesDir, detail.slug);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = `${detail.slug}-${timestamp}.tar.gz`;

    if (detail.target.type === 'ssh') {
      const backupDir = path.posix.join(detail.target.remotePath, 'backups');
      const remoteFile = path.posix.join(backupDir, filename);
      const adapter = this.createAdapter(detail.target);
      if (!adapter.createRemoteBackup) {
        throw new Error('当前远程适配器不支持备份');
      }
      await adapter.createRemoteBackup(detail.target.remotePath, remoteFile);
      await this.repository.addBackup(projectId, filename, remoteFile, 0);
      return `远程备份已创建：${remoteFile}`;
    }

    const backupFile = path.join(paths.backupsDir, filename);
    await fs.mkdir(paths.backupsDir, { recursive: true });
    await fs.cp(paths.dataDir, path.join(paths.backupsDir, `${detail.slug}-snapshot`), {
      recursive: true,
      force: true,
    });
    const { runCommand } = await import('../utils/command');
    const result = await runCommand('tar', ['-czf', backupFile, '-C', paths.root, 'data']);
    await fs.rm(path.join(paths.backupsDir, `${detail.slug}-snapshot`), { recursive: true, force: true });
    if (!result.ok) {
      throw new Error(result.stderr || '本地备份失败');
    }
    const sizeBytes = statSync(backupFile).size;
    await this.repository.addBackup(projectId, filename, backupFile, sizeBytes);
    await this.trimBackups(projectId, paths.backupsDir);
    return `本地备份已创建：${backupFile}`;
  }

  private async trimBackups(projectId: string, backupsDir: string) {
    const records = await this.repository.listBackups(projectId);
    for (const record of records.slice(10)) {
      try {
        await fs.rm(path.join(backupsDir, record.filename), { force: true });
      } catch {
        // 忽略磁盘删除失败，继续清理数据库记录
      }
      await this.repository.removeBackupRecord(record.id);
    }
  }

  private publishTaskProgress(projectId: string, taskId: string, action: ProjectAction, message: string) {
    this.eventBus.publishTask({
      type: 'task.progress',
      projectId,
      taskId,
      action,
      message,
      timestamp: new Date().toISOString(),
    });
  }

  private publishActionLog(projectId: string, line: string, stream: 'stdout' | 'stderr' | 'system') {
    this.eventBus.publishLog({
      type: 'log.line',
      projectId,
      line,
      stream,
      timestamp: new Date().toISOString(),
    });
  }
}

function joinMessages(...parts: Array<string | null | undefined>) {
  return parts
    .map((part) => part?.trim())
    .filter((part): part is string => !!part)
    .join('\n');
}

async function writeRenderedFiles(
  configDir: string,
  preview: Record<string, string>,
) {
  for (const [relativePath, content] of Object.entries(preview)) {
    const filePath = path.join(configDir, relativePath);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, content, 'utf8');
  }
}

async function writeClusterRuntimeFiles(
  clusterDir: string,
  preview: Record<string, string>,
) {
  const mappings: Record<string, string> = {
    'cluster.ini': path.join(clusterDir, 'cluster.ini'),
    'cluster_token.txt': path.join(clusterDir, 'cluster_token.txt'),
    'Master/server.ini': path.join(clusterDir, 'Master', 'server.ini'),
    'Caves/server.ini': path.join(clusterDir, 'Caves', 'server.ini'),
    'Master/worldgenoverride.lua': path.join(clusterDir, 'Master', 'worldgenoverride.lua'),
    'Caves/worldgenoverride.lua': path.join(clusterDir, 'Caves', 'worldgenoverride.lua'),
    'adminlist.txt': path.join(clusterDir, 'adminlist.txt'),
  };

  for (const [source, target] of Object.entries(mappings)) {
    const content = preview[source];
    if (typeof content !== 'string') {
      continue;
    }
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, content, 'utf8');
  }
}

function normalizeTarget(target: TargetConfig, slug: string): TargetConfig {
  const parsed = TargetConfigSchema.parse(target);
  if (parsed.type === 'ssh') {
    return {
      ...parsed,
      remotePath: parsed.remotePath?.trim() || createRemoteDeployPath(slug),
    };
  }
  return parsed;
}

// Fixed ports used by the wollwolke/dst-dedicated-server Docker image
const DOCKER_FIXED_PORTS = [11000, 27016, 8766, 10999, 27017, 8767];

function getProjectPorts(config: ClusterConfig, targetType?: string): number[] {
  if (targetType && targetType !== 'native') {
    return DOCKER_FIXED_PORTS;
  }
  return [
    config.master.serverPort,
    config.master.masterServerPort,
    config.master.authenticationPort,
    config.caves.serverPort,
    config.caves.masterServerPort,
    config.caves.authenticationPort,
  ];
}

async function collectLocalStats(diskPath: string): Promise<ServerStats> {
  const memTotal = os.totalmem();
  const memFree = os.freemem();
  const loadAvg = os.loadavg();
  const cpuCount = os.cpus().length;

  let swapTotal = 0;
  let swapUsed = 0;
  try {
    const meminfo = await fs.readFile('/proc/meminfo', 'utf8');
    const swapTotalKb = Number(/SwapTotal:\s+(\d+)/.exec(meminfo)?.[1] ?? 0);
    const swapFreeKb = Number(/SwapFree:\s+(\d+)/.exec(meminfo)?.[1] ?? 0);
    swapTotal = swapTotalKb * 1024;
    swapUsed = (swapTotalKb - swapFreeKb) * 1024;
  } catch {
    // non-Linux: no swap info
  }

  const dfResult = await runCommand('df', ['-Pk', diskPath]);
  let diskTotal = 0;
  let diskUsed = 0;
  let resolvedDiskPath = diskPath;
  if (dfResult.ok) {
    const lines = dfResult.stdout.trim().split('\n');
    const dataLine = lines[1]?.trim().split(/\s+/) ?? [];
    diskTotal = Number(dataLine[1] ?? 0) * 1024;
    diskUsed = Number(dataLine[2] ?? 0) * 1024;
    resolvedDiskPath = dataLine[5] ?? diskPath;
  }

  return {
    cpu: { loadAvg1: loadAvg[0] ?? 0, cpuCount },
    memory: { total: memTotal, used: memTotal - memFree },
    swap: { total: swapTotal, used: swapUsed },
    disk: { total: diskTotal, used: diskUsed, path: resolvedDiskPath },
    collectedAt: new Date().toISOString(),
  };
}

async function collectRemoteStats(target: import('@dst-launcher/shared').SshTargetConfig): Promise<ServerStats> {
  const sshArgs = [
    '-i', target.privateKeyPath,
    '-p', String(target.port),
    '-o', 'BatchMode=yes',
    `${target.username}@${target.host}`,
    `uptime && echo '---CPUS---' && nproc && echo '---MEM---' && cat /proc/meminfo && echo '---DF---' && df -Pk ${target.remotePath || '/'}`,
  ];

  const result = await runCommand('ssh', sshArgs);
  if (!result.ok) {
    return {
      cpu: { loadAvg1: 0, cpuCount: 0 },
      memory: { total: 0, used: 0 },
      swap: { total: 0, used: 0 },
      disk: { total: 0, used: 0, path: target.remotePath || '/' },
      collectedAt: new Date().toISOString(),
    };
  }

  const out = result.stdout;
  const loadMatch = /load average:\s*([\d.]+)/.exec(out);
  const loadAvg1 = Number(loadMatch?.[1] ?? 0);

  const cpusPart = out.split('---CPUS---')[1]?.split('---MEM---')[0] ?? '';
  const cpuCount = Number(cpusPart.trim()) || 0;

  const memPart = out.split('---MEM---')[1]?.split('---DF---')[0] ?? '';
  const dfPart = out.split('---DF---')[1] ?? '';

  const memTotalKb = Number(/MemTotal:\s+(\d+)/.exec(memPart)?.[1] ?? 0);
  const memAvailKb = Number(/MemAvailable:\s+(\d+)/.exec(memPart)?.[1] ?? 0);
  const swapTotalKb = Number(/SwapTotal:\s+(\d+)/.exec(memPart)?.[1] ?? 0);
  const swapFreeKb = Number(/SwapFree:\s+(\d+)/.exec(memPart)?.[1] ?? 0);

  const dfLines = dfPart.trim().split('\n');
  const dfData = dfLines[1]?.trim().split(/\s+/) ?? [];
  const diskTotal = Number(dfData[1] ?? 0) * 1024;
  const diskUsed = Number(dfData[2] ?? 0) * 1024;
  const diskPath = dfData[5] ?? target.remotePath ?? '/';

  return {
    cpu: { loadAvg1, cpuCount },
    memory: { total: memTotalKb * 1024, used: (memTotalKb - memAvailKb) * 1024 },
    swap: { total: swapTotalKb * 1024, used: (swapTotalKb - swapFreeKb) * 1024 },
    disk: { total: diskTotal, used: diskUsed, path: diskPath },
    collectedAt: new Date().toISOString(),
  };
}
